### ISSUE TITLE
It works, but how to use?

### ISSUE THREAD

**Issue by kenara** [johnnybui/prerender-firebase-cache#1]
I installed the plugin and changed the server.js according to README.

I visit my URL: http://localhost:3000/https://www.example.com/ and now I have a "cache" node in my Firebase with the cached page. It worked perfectly - that was easy, thanks!

But my site is hosted on Firebase hosting. I want to serve cached, prerendered pages to Googlebot. 

How can I do that?

**Comment by johnnybui** [comment]
You cannot do that with only Firebase hosting because it's just a static host. To serve prerendered pages you have to config with nginx or whatever HTTP server.

If you still want to serve your web app on Firebase hosting you need HTTP server such as nginx, node and config it proxy pass your Firebase hosting when meet bots.

**Comment by kenara** [comment]
OK... I was thinking maybe the plugin could be used together with prerender.io 
https://github.com/prerender/prerender-node - then the cached pages would reduce the cost?

see also my question on stackoverflow:
https://stackoverflow.com/questions/56665898/googlebot-cant-see-data-loaded-from-firebase

**Comment by kenara** [comment]
I am working on this based on your advice so I'll close this issue (wasn't really an issue).

If I get really stuck, I might "challenge" your company for help! :-)
